apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: nats
  name: nats
spec:
  containers:
  - args:
    - -c
    - /etc/nats/nats.conf
    image: nats:1.3.0
    name: mainflux-nats
    resources: {}
    volumeMounts:
    - mountPath: /etc/nats
      name: nats-claim0
  restartPolicy: OnFailure
  volumes:
  - name: nats-claim0
    persistentVolumeClaim:
      claimName: nats-claim0
status: {}
